sonar.projectKey=minuta_contractual_mid
sonar.projectName=minuta_contractual_mid
sonar.projectVersion=0.0.1

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,swagger/**

sonar.sourceEncoding=UTF-8
